[[constraint]]
  branch = "master"
  name = "github.com/hashicorp/vault"

[[constraint]]
  name = "github.com/mgutz/logxi"
  version = "1.0.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/sethvargo/go-diceware"

[[constraint]]
  branch = "master"
  name = "github.com/sethvargo/go-password"
